# SPDX-FileCopyrightText: 2026 Dawid Papiewski "SpacingBat3" <spacingbat3@gmail.com>
#
# SPDX-License-Identifier: LGPL-3.0-or-later OR GPL-3.0-or-later

### METADATA ###

[package]
name        = "kontur"
version     = "0.1.2"
description = "A terminal manipulation library for CLI applications."
license     = "LGPL-3.0-or-later OR GPL-3.0-or-later"
homepage    = "https://github.com/SpacingBat3/Kontur.rs#readme"
repository  = "https://github.com/SpacingBat3/Kontur.rs"
categories  = ["command-line-interface", "text-processing", "value-formatting"]
keywords    = ["ansi","color","wrap","line","argv"]
readme      = "docs/Readme.md"
edition     = "2024"
exclude     = [
    ".gitignore", # dev-only
    "LICENSE.*",  # GitHub representation, preffer REUSE
    "docs/**",    # keep docs minimal
]

[features]
default = ["unicode"]
ascii   = []
unicode = ["dep:unicode-width"]

### DEPENDENCIES ###

[dependencies.unicode-width]
version          = "0.2"
default-features = false
optional         = true

[target.'cfg(unix)'.dependencies.libc]
version = "0.2"

[target.'cfg(windows)'.dependencies.windows]
version  = "0.62"
features = ["Win32_System_Console"]
